services:
  order-db:
    image: postgres:17
    container_name: order-db
    environment:
      POSTGRES_DB: ecommerce_orders
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - order_db_data:/var/lib/postgresql/data

volumes:
  order_db_data:
