spring.application.name=product-service
spring.config.import=configserver:http://localhost:8888

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_products
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false
