spring:
  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: order-activity-service
      auto-offset-reset: latest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer

      properties:
        "[spring.json.trusted.packages]": "com.ecommerce.orderactivity.event"
        "[spring.json.value.default.type]": "com.ecommerce.orderactivity.event.OrderCreatedEvent"
        "[spring.json.use.type.headers]": false

app:
  dynamodb:
    endpoint: http://localhost:8000
    region: us-east-1
    table-name: order-activity
