spring.application.name=claims-service
spring.config.import=configserver:http://localhost:8888

spring.datasource.url=jdbc:postgresql://localhost:5433/insurance_claims
spring.datasource.username=postgres
spring.datasource.password=postgres

#policy.service.url=http://localhost:8081
#dont need this when running Eureka

spring.jpa.hibernate.ddl-auto=validate

eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false