services:
  claims-db:
    image: postgres:17
    container_name: claims-db
    environment:
      POSTGRES_DB: insurance_claims
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - claims_db_data:/var/lib/postgresql/data

volumes:
  claims_db_data: