services:
  policy-db:
    image: postgres:17
    container_name: policy-db
    environment:
      POSTGRES_DB: insurance_policy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - policy_db_data:/var/lib/postgresql/data

volumes:
  policy_db_data: